ALTER TABLE product DROP COLUMN id;
ALTER TABLE product ADD COLUMN id serial PRIMARY KEY;
ALTER TABLE "user" DROP COLUMN id;
ALTER TABLE "user" ADD COLUMN id serial PRIMARY KEY;
ALTER TABLE authority DROP COLUMN id;
ALTER TABLE authority ADD COLUMN id serial PRIMARY KEY;